vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        cars:
            uri_prefix: /images/cars
            upload_destination: '%kernel.project_dir%/public/images/cars'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
            delete_on_update: true
            inject_on_load: true
